steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-agent', './api-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/scraper-agent', './scraper-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/retriever-agent', './retriever-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/lang-agent', './lang-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/streamlit-app', './streamlit-app']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/api-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/scraper-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/retriever-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/lang-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/streamlit-app']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'api-agent'
  - '--image'
  - 'gcr.io/$PROJECT_ID/api-agent'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '512Mi'
  - '--cpu'
  - '1'
  - '--set-env-vars'
  - 'HUGGINGFACE_API_KEY=${_HUGGINGFACE_API_KEY}'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'scraper-agent'
  - '--image'
  - 'gcr.io/$PROJECT_ID/scraper-agent'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '512Mi'
  - '--cpu'
  - '1'
  - '--set-env-vars'
  - 'HUGGINGFACE_API_KEY=${_HUGGINGFACE_API_KEY}'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'retriever-agent'
  - '--image'
  - 'gcr.io/$PROJECT_ID/retriever-agent'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '1Gi'
  - '--cpu'
  - '1'
  - '--set-env-vars'
  - 'HUGGINGFACE_API_KEY=${_HUGGINGFACE_API_KEY},PINECONE_API_KEY=${_PINECONE_API_KEY},PINECONE_ENVIRONMENT=${_PINECONE_ENVIRONMENT},PINECONE_INDEX=${_PINECONE_INDEX}'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'lang-agent'
  - '--image'
  - 'gcr.io/$PROJECT_ID/lang-agent'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '2Gi'
  - '--cpu'
  - '2'
  - '--set-env-vars'
  - 'HUGGINGFACE_API_KEY=${_HUGGINGFACE_API_KEY}'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'streamlit-app'
  - '--image'
  - 'gcr.io/$PROJECT_ID/streamlit-app'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '512Mi'
  - '--cpu'
  - '1'
  - '--set-env-vars'
  - 'HUGGINGFACE_API_KEY=${_HUGGINGFACE_API_KEY}'

substitutions:
  _HUGGINGFACE_API_KEY: ''  # Set in Cloud Build triggers
  _PINECONE_API_KEY: ''     # Set in Cloud Build triggers
  _PINECONE_ENVIRONMENT: '' # Set in Cloud Build triggers
  _PINECONE_INDEX: ''       # Set in Cloud Build triggers 