apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-agent
  namespace: finseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-agent
  template:
    metadata:
      labels:
        app: api-agent
    spec:
      containers:
      - name: api-agent
        image: python:3.11-slim
        ports:
        - containerPort: 8000
        workingDir: /app
        command: ["/bin/bash"]
        args: ["-c", "pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 yfinance==0.2.28 pandas==2.1.4 requests==2.31.0 && uvicorn api:app --host 0.0.0.0 --port 8000"]
        env:
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: huggingface-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        volumeMounts:
        - name: api-agent-code
          mountPath: /app
      volumes:
      - name: api-agent-code
        configMap:
          name: api-agent-code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-agent
  namespace: finseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-agent
  template:
    metadata:
      labels:
        app: scraper-agent
    spec:
      containers:
      - name: scraper-agent
        image: python:3.11-slim
        ports:
        - containerPort: 8001
        workingDir: /app
        command: ["/bin/bash"]
        args: ["-c", "pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 requests==2.31.0 beautifulsoup4==4.12.2 pandas==2.1.4 && uvicorn scraper:app --host 0.0.0.0 --port 8001"]
        env:
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: huggingface-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        volumeMounts:
        - name: scraper-agent-code
          mountPath: /app
      volumes:
      - name: scraper-agent-code
        configMap:
          name: scraper-agent-code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retriever-agent
  namespace: finseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retriever-agent
  template:
    metadata:
      labels:
        app: retriever-agent
    spec:
      containers:
      - name: retriever-agent
        image: python:3.11-slim
        ports:
        - containerPort: 8002
        workingDir: /app
        command: ["/bin/bash"]
        args: ["-c", "pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 pinecone-client==2.2.4 sentence-transformers==2.2.2 pandas==2.1.4 && uvicorn retriever:app --host 0.0.0.0 --port 8002"]
        env:
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: huggingface-api-key
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: pinecone-api-key
        - name: PINECONE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: finseek-config
              key: pinecone-environment
        - name: PINECONE_INDEX
          valueFrom:
            configMapKeyRef:
              name: finseek-config
              key: pinecone-index
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: retriever-agent-code
          mountPath: /app
      volumes:
      - name: retriever-agent-code
        configMap:
          name: retriever-agent-code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lang-agent
  namespace: finseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lang-agent
  template:
    metadata:
      labels:
        app: lang-agent
    spec:
      containers:
      - name: lang-agent
        image: python:3.11-slim
        ports:
        - containerPort: 8003
        workingDir: /app
        command: ["/bin/bash"]
        args: ["-c", "apt-get update && apt-get install -y ffmpeg espeak-ng alsa-utils && pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 torch==2.1.0 transformers==4.35.0 pyttsx3==2.90 openai-whisper==20231117 && uvicorn lang:app --host 0.0.0.0 --port 8003"]
        env:
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: huggingface-api-key
        resources:
          requests:
            memory: "1Gi"
            cpu: "300m"
          limits:
            memory: "2Gi"
            cpu: "800m"
        volumeMounts:
        - name: lang-agent-code
          mountPath: /app
      volumes:
      - name: lang-agent-code
        configMap:
          name: lang-agent-code 