apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-agent
  namespace: finseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-agent
  template:
    metadata:
      labels:
        app: api-agent
    spec:
      containers:
      - name: api-agent
        image: python:3.11-slim
        ports:
        - containerPort: 8000
        workingDir: /app
        command: ["/bin/bash"]
        args: ["-c", "pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 yfinance==0.2.28 pandas==2.1.4 requests==2.31.0 && uvicorn api:app --host 0.0.0.0 --port 8000"]
        env:
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: huggingface-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: api-agent-code
          mountPath: /app
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 90
          periodSeconds: 20
      volumes:
      - name: api-agent-code
        configMap:
          name: api-agent-code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-agent
  namespace: finseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-agent
  template:
    metadata:
      labels:
        app: scraper-agent
    spec:
      containers:
      - name: scraper-agent
        image: python:3.11-slim
        ports:
        - containerPort: 8001
        workingDir: /app
        command: ["/bin/bash"]
        args: ["-c", "pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 requests==2.31.0 beautifulsoup4==4.12.2 pandas==2.1.4 sec-cik-mapper && uvicorn scraper_agent:app --host 0.0.0.0 --port 8001"]
        env:
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: huggingface-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: scraper-agent-code
          mountPath: /app
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 120
          periodSeconds: 20
      volumes:
      - name: scraper-agent-code
        configMap:
          name: scraper-agent-code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retriever-agent
  namespace: finseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retriever-agent
  template:
    metadata:
      labels:
        app: retriever-agent
    spec:
      containers:
      - name: retriever-agent
        image: python:3.11-slim
        ports:
        - containerPort: 8002
        workingDir: /app
        command: ["/bin/bash"]
        args: ["-c", "pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 pinecone-client==2.2.4 sentence-transformers==2.2.2 pandas==2.1.4 && uvicorn retriver_agent:app --host 0.0.0.0 --port 8002"]
        env:
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: huggingface-api-key
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: pinecone-api-key
        - name: PINECONE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: finseek-config
              key: pinecone-environment
        - name: PINECONE_INDEX
          valueFrom:
            configMapKeyRef:
              name: finseek-config
              key: pinecone-index
        - name: PORTFOLIO_PATH
          value: "/data/portfolio.csv"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        volumeMounts:
        - name: retriever-agent-code
          mountPath: /app
        - name: portfolio-data
          mountPath: /data
          readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 150
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 300
          periodSeconds: 40
          timeoutSeconds: 10
          failureThreshold: 5
      volumes:
      - name: retriever-agent-code
        configMap:
          name: retriever-agent-code
      - name: portfolio-data
        configMap:
          name: portfolio-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lang-agent
  namespace: finseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lang-agent
  template:
    metadata:
      labels:
        app: lang-agent
    spec:
      containers:
      - name: lang-agent
        image: python:3.11-slim
        ports:
        - containerPort: 8003
        workingDir: /app
        command: ["/bin/bash"]
        args: ["-c", "apt-get update && apt-get install -y espeak-ng && pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 python-multipart==0.0.6 requests==2.31.0 && uvicorn lang_agent:app --host 0.0.0.0 --port 8003"]
        env:
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: huggingface-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        volumeMounts:
        - name: lang-agent-code
          mountPath: /app
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 45
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 90
          periodSeconds: 20
      volumes:
      - name: lang-agent-code
        configMap:
          name: lang-agent-code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: finseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: python:3.11-slim
        ports:
        - containerPort: 8004
        workingDir: /app
        command: ["/bin/bash"]
        args: ["-c", "pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 httpx==0.25.2 pandas==2.1.4 && uvicorn orchestrator:app --host 0.0.0.0 --port 8004"]
        env:
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: huggingface-api-key
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        volumeMounts:
        - name: orchestrator-code
          mountPath: /app
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 240
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
      volumes:
      - name: orchestrator-code
        configMap:
          name: orchestrator-code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  namespace: finseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: python:3.11-slim
        ports:
        - containerPort: 8501
        workingDir: /app
        command: ["/bin/bash"]
        args: ["-c", "pip install streamlit==1.28.1 requests==2.31.0 pandas==2.1.4 audio-recorder-streamlit==0.0.8 && streamlit run app.py --server.port=8501 --server.address=0.0.0.0"]
        env:
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: finseek-secrets
              key: huggingface-api-key
        - name: ORCHESTRATOR_URL
          value: "http://orchestrator-service:8004"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: streamlit-app-code
          mountPath: /app
        - name: portfolio-data
          mountPath: /data
          readOnly: true
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 120
          periodSeconds: 20
      volumes:
      - name: streamlit-app-code
        configMap:
          name: streamlit-app-code
      - name: portfolio-data
        configMap:
          name: portfolio-data 