apiVersion: v1
kind: Secret
metadata:
  name: finseek-secrets
  namespace: finseek
type: Opaque
stringData:
  huggingface-api-key: "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"
  pinecone-api-key: "your-pinecone-key-here"
  alpha-vantage-api-key: "your-alpha-vantage-key-here"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: finseek-config
  namespace: finseek
data:
  pinecone-environment: "us-east1-gcp"
  pinecone-index: "finance-agent" 