apiVersion: v1
kind: Service
metadata:
  name: api-agent
spec:
  selector:
    app: api-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: scraper-agent
spec:
  selector:
    app: scraper-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: retriever-agent
spec:
  selector:
    app: retriever-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: lang-agent
spec:
  selector:
    app: lang-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app
spec:
  selector:
    app: streamlit-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer 