apiVersion: v1
kind: Service
metadata:
  name: api-agent-service
  namespace: finseek
spec:
  selector:
    app: api-agent
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: scraper-agent-service
  namespace: finseek
spec:
  selector:
    app: scraper-agent
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: retriever-agent-service
  namespace: finseek
spec:
  selector:
    app: retriever-agent
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: lang-agent-service
  namespace: finseek
spec:
  selector:
    app: lang-agent
  ports:
  - port: 8003
    targetPort: 8003
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  namespace: finseek
spec:
  selector:
    app: orchestrator
  ports:
  - port: 8004
    targetPort: 8004
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
  namespace: finseek
spec:
  selector:
    app: streamlit-app
  ports:
  - port: 8501
    targetPort: 8501
  type: LoadBalancer 